//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _06OctoberAssignement_Adomvc_modelBinding
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Constraints1
    {
        public string CONSTRAINT_TYPE { get; set; }
        public string CONSTRAINT_NAME { get; set; }
    }
}
